### ISSUE TITLE
Compatibility with PHP 7.3+

### ISSUE THREAD

**Issue by nicti** [saleslayer/Sales_Layer_Magento2#3]
Hi,

I am getting the following error when running setup:di:compile:

> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /srv/projects/sohandel/htdocs/so-handel/magento/app/code/Saleslayer/Synccatalog/Model/Synccatalog.php on line 3878

This is a migration problem of PHP7.2 -> PHP7.3:
[https://www.php.net/manual/de/migration73.incompatible.php](https://www.php.net/manual/de/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch)

According to [Magento System Requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php) PHP 7.3 is recommended for Magento 2.3.

Can you adjust your code to work with PHP7.3+?

Thanks in advance,
Niclas Titius

**Comment by moreno24** [comment]
Hi again @nicti ,

All continues have been removed from switches as you mentioned.
We tested with PHP 7.3 and found no further issues.

Thanks for the feedback :)
